version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2

aliases:
  - &restore-cache
    restore_cache:
      key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
  - &install-pnpm
    run:
      name: Install pnpm
      command: corepack enable && corepack prepare pnpm@10.5.2 --activate
  - &install-deps
    run:
      name: Install dependencies
      command: pnpm install --frozen-lockfile
  - &build-packages
    run:
      name: Build
      command: pnpm run build

jobs:
  build:
    working_directory: ~/nodejs-order-book
    docker:
      - image: cimg/node:22.5
    steps:
      - checkout
      - *restore-cache
      - *install-pnpm
      - *install-deps
      - save_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ./node_modules
      - *build-packages

  test:
    working_directory: ~/nodejs-order-book
    docker:
      - image: cimg/node:22.5
    steps:
      - checkout
      - *restore-cache
      - *install-pnpm
      - *install-deps
      - run:
          name: Unit tests
          command: pnpm -r run test:cov
      - codecov/upload:
          file: './packages/*/coverage/lcov.info'

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build