version: 2.1

orbs:
  codecov: codecov/codecov@6.0.0

aliases:
  - &restore-cache
    restore_cache:
      key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}

  - &install-pnpm
    run:
      name: Install pnpm
      command: |
        curl -fsSL https://get.pnpm.io/install.sh | sh -
        echo 'export PNPM_HOME="$HOME/.local/share/pnpm"' >> "$BASH_ENV"
        echo 'export PATH="$PNPM_HOME:$PATH"' >> "$BASH_ENV"
        source "$BASH_ENV"
        pnpm --version

  - &install-deps
    run:
      name: Install dependencies
      command: pnpm install --frozen-lockfile

  - &build-packages
    run:
      name: Build
      command: pnpm run build

jobs:
  build:
    working_directory: ~/nodejs-order-book
    docker:
      - image: cimg/node:24.19
    steps:
      - checkout
      - *restore-cache
      - *install-pnpm
      - *install-deps
      - save_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ./node_modules
      - *build-packages

  test:
    working_directory: ~/nodejs-order-book
    docker:
      - image: cimg/node:24.19
    steps:
      - checkout
      - *restore-cache
      - *install-pnpm
      - *install-deps
      - run:
          name: Unit tests
          command: pnpm -r run test:cov
      - codecov/upload:
          files: './packages/*/coverage/lcov.info'

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build